// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package jni.manager;


public class GnsdkErrors
{

    public static int A;
    public static int B;
    public static int C;
    public static int D;
    public static int E;
    public static int F;
    public static int G;
    public static int H;
    public static int I;
    public static int J;
    public static int K;
    public static int L;
    public static int M;
    public static int N;
    public static int O;
    public static int P;
    public static int Q;
    public static int R;
    public static int S;
    public static int T;
    public static int U;
    public static int V;
    public static int W;
    public static int X;
    public static int Y;
    public static int Z;
    public static int a;
    public static int aA;
    public static int aB;
    public static int aC;
    public static int aD;
    public static int aE;
    public static int aF;
    public static int aG;
    public static int aH;
    public static int aI;
    public static int aJ;
    public static int aK;
    public static int aL;
    public static int aM;
    public static int aN;
    public static int aO;
    public static int aP;
    public static int aQ;
    public static int aR;
    public static int aS;
    public static int aT;
    public static int aU;
    public static int aV;
    public static int aW;
    public static int aX;
    public static int aY;
    public static int aZ;
    public static int aa;
    public static int ab;
    public static int ac;
    public static int ad;
    public static int ae;
    public static int af;
    public static int ag;
    public static int ah;
    public static int ai;
    public static int aj;
    public static int ak;
    public static int al;
    public static int am;
    public static int an;
    public static int ao;
    public static int ap;
    public static int aq;
    public static int ar;
    public static int as;
    public static int at;
    public static int au;
    public static int av;
    public static int aw;
    public static int ax;
    public static int ay;
    public static int az;
    public static int b;
    public static int bA;
    public static int bB;
    public static int bC;
    public static int bD;
    public static int bE;
    public static int bF;
    public static int bG;
    public static int bH;
    public static int bI;
    public static int bJ;
    public static int bK;
    public static int bL;
    public static int bM;
    public static int bN;
    public static int bO;
    public static int bP;
    public static int bQ;
    public static int bR;
    public static int bS;
    public static int bT;
    public static int bU;
    public static int bV;
    public static int bW;
    public static int bX;
    public static int bY;
    public static int bZ;
    public static int ba;
    public static int bb;
    public static int bc;
    public static int bd;
    public static int be;
    public static int bf;
    public static int bg;
    public static int bh;
    public static int bi;
    public static int bj;
    public static int bk;
    public static int bl;
    public static int bm;
    public static int bn;
    public static int bo;
    public static int bp;
    public static int bq;
    public static int br;
    public static int bs;
    public static int bt;
    public static int bu;
    public static int bv;
    public static int bw;
    public static int bx;
    public static int by;
    public static int bz;
    public static int c;
    public static int cA;
    public static int cB;
    public static int cC;
    public static int cD;
    public static int cE;
    public static int cF;
    public static int cG;
    public static int cH;
    public static int cI;
    public static int cJ;
    public static int cK;
    public static int cL;
    public static int cM;
    public static int cN;
    public static int cO;
    public static int cP;
    public static int cQ;
    public static int cR;
    public static int cS;
    public static int cT;
    public static int cU;
    public static int cV;
    public static int cW;
    public static int cX;
    public static int cY;
    public static int cZ;
    public static int ca;
    public static int cb;
    public static int cc;
    public static int cd;
    public static int ce;
    public static int cf;
    public static int cg;
    public static int ch;
    public static int ci;
    public static int cj;
    public static int ck;
    public static int cl;
    public static int cm;
    public static int cn;
    public static int co;
    public static int cp;
    public static int cq;
    public static int cr;
    public static int cs;
    public static int ct;
    public static int cu;
    public static int cv;
    public static int cw;
    public static int cx;
    public static int cy;
    public static int cz;
    public static int d;
    public static int dA;
    public static int dB;
    public static int dC;
    public static int dD;
    public static int dE;
    public static int dF;
    public static int dG;
    public static int dH;
    public static int dI;
    public static int dJ;
    public static int dK;
    public static int dL;
    public static int dM;
    public static int dN;
    public static int dO;
    public static int dP;
    public static int dQ;
    public static int dR;
    public static int dS;
    public static int dT;
    public static int dU;
    public static int dV;
    public static int dW;
    public static int dX;
    public static int dY;
    public static int dZ;
    public static int da;
    public static int db;
    public static int dc;
    public static int dd;
    public static int de;
    public static int df;
    public static int dg;
    public static int dh;
    public static int di;
    public static int dj;
    public static int dk;
    public static int dl;
    public static int dm;
    public static int dn;
    public static int _flddo;
    public static int dp;
    public static int dq;
    public static int dr;
    public static int ds;
    public static int dt;
    public static int du;
    public static int dv;
    public static int dw;
    public static int dx;
    public static int dy;
    public static int dz;
    public static int e;
    public static int eA;
    public static int eB;
    public static int eC;
    public static int eD;
    public static int eE;
    public static int eF;
    public static int eG;
    public static int eH;
    public static int eI;
    public static int eJ;
    public static int eK;
    public static int eL;
    public static int eM;
    public static int eN;
    public static int eO;
    public static int eP;
    public static int eQ;
    public static int eR;
    public static int eS;
    public static int eT;
    public static int eU;
    public static int eV;
    public static int eW;
    public static int eX;
    public static int eY;
    public static int eZ;
    public static int ea;
    public static int eb;
    public static int ec;
    public static int ed;
    public static int ee;
    public static int ef;
    public static int eg;
    public static int eh;
    public static int ei;
    public static int ej;
    public static int ek;
    public static int el;
    public static int em;
    public static int en;
    public static int eo;
    public static int ep;
    public static int eq;
    public static int er;
    public static int es;
    public static int et;
    public static int eu;
    public static int ev;
    public static int ew;
    public static int ex;
    public static int ey;
    public static int ez;
    public static int f;
    public static int fA;
    public static int fB;
    public static int fC;
    public static int fD;
    public static int fE;
    public static int fF;
    public static int fG;
    public static int fH;
    public static int fI;
    public static int fJ;
    public static int fK;
    public static int fL;
    public static int fM;
    public static int fN;
    public static int fO;
    public static int fP;
    public static int fQ;
    public static int fR;
    public static int fS;
    public static int fT;
    public static int fU;
    public static int fV;
    public static int fW;
    public static int fX;
    public static int fY;
    public static int fZ;
    public static int fa;
    public static int fb;
    public static int fc;
    public static int fd;
    public static int fe;
    public static int ff;
    public static int fg;
    public static int fh;
    public static int fi;
    public static int fj;
    public static int fk;
    public static int fl;
    public static int fm;
    public static int fn;
    public static int fo;
    public static int fp;
    public static int fq;
    public static int fr;
    public static int fs;
    public static int ft;
    public static int fu;
    public static int fv;
    public static int fw;
    public static int fx;
    public static int fy;
    public static int fz;
    public static int g;
    public static int gA;
    public static int gB;
    public static int gC;
    public static int gD;
    public static int gE;
    public static int gF;
    public static int gG;
    public static int gH;
    public static int gI;
    public static int gJ;
    public static int gK;
    public static int gL;
    public static int gM;
    public static int gN;
    private static int gO;
    private static int gP;
    private static int gQ;
    private static int gR;
    private static int gS;
    private static int gT;
    private static int gU;
    private static int gV;
    private static int gW;
    private static int gX;
    private static int gY;
    private static int gZ;
    public static int ga;
    public static int gb;
    public static int gc;
    public static int gd;
    public static int ge;
    public static int gf;
    public static int gg;
    public static int gh;
    public static int gi;
    public static int gj;
    public static int gk;
    public static int gl;
    public static int gm;
    public static int gn;
    public static int go;
    public static int gp;
    public static int gq;
    public static int gr;
    public static int gs;
    public static int gt;
    public static int gu;
    public static int gv;
    public static int gw;
    public static int gx;
    public static int gy;
    public static int gz;
    public static int h;
    public static int i;
    public static int j;
    public static int k;
    public static int l;
    public static int m;
    public static int n;
    public static int o;
    public static int p;
    public static int q;
    public static int r;
    public static int s;
    public static int t;
    public static int u;
    public static int v;
    public static int w;
    public static int x;
    public static int y;
    public static int z;

    public static int a(int i1)
    {
        return (0xffff & i1) >> 0 & 0x1ffff;
    }

    private static int a(int i1, int j1)
    {
        return 0x90000000 | i1 << 16 | j1 << 0;
    }

    private static int b(int i1, int j1)
    {
        return 0x10000000 | i1 << 16 | j1 << 0;
    }

    public static boolean b(int i1)
    {
        return (0x80000000 & i1) >> 31 != 0;
    }

    static 
    {
        gO = 128;
        a = 253;
        gP = gO + 0;
        gQ = gO + 1;
        gR = gO + 2;
        gS = gO + 4;
        gT = gO + 5;
        gU = gO + 9;
        gV = gO + 6;
        gW = gO + 7;
        gX = gO + 32;
        gY = gO + 33;
        b = gO + 64;
        c = a;
        gZ = 0;
        d = 0;
        e = gZ + 1;
        f = gZ + 2;
        g = gZ + 3;
        h = gZ + 4;
        i = gZ + 5;
        j = gZ + 6;
        k = gZ + 7;
        l = gZ + 8;
        m = gZ + 9;
        n = gZ + 10;
        o = gZ + 11;
        p = gZ + 12;
        q = gZ + 13;
        r = gZ + 60;
        s = gZ + 61;
        t = gZ + 62;
        u = gZ + 63;
        v = gZ + 64;
        w = gZ + 65;
        x = gZ + 66;
        y = gZ + 67;
        z = gZ + 68;
        A = gZ + 69;
        B = gZ + 70;
        C = gZ + 71;
        D = gZ + 72;
        E = gZ + 128;
        F = gZ + 129;
        G = gZ + 130;
        H = gZ + 131;
        I = gZ + 132;
        J = gZ + 133;
        K = gZ + 134;
        L = gZ + 135;
        M = gZ + 136;
        N = gZ + 137;
        O = gZ + 138;
        P = gZ + 192;
        Q = gZ + 193;
        R = gZ + 194;
        S = gZ + 195;
        T = gZ + 196;
        U = gZ + 288;
        V = gZ + 289;
        W = gZ + 290;
        X = gZ + 291;
        Y = gZ + 292;
        Z = gZ + 352;
        aa = gZ + 353;
        ab = gZ + 354;
        ac = gZ + 355;
        ad = gZ + 356;
        ae = gZ + 357;
        af = gZ + 358;
        ag = gZ + 359;
        ah = gZ + 416;
        ai = gZ + 417;
        aj = gZ + 418;
        ak = gZ + 419;
        al = gZ + 420;
        am = gZ + 512;
        an = gZ + 513;
        ao = gZ + 514;
        ap = gZ + 515;
        aq = gZ + 516;
        ar = gZ + 517;
        as = gZ + 518;
        at = gZ + 519;
        au = gZ + 520;
        av = gZ + 521;
        aw = gZ + 576;
        ax = gZ + 640;
        ay = gZ + 641;
        az = gZ + 642;
        aA = gZ + 643;
        aB = gZ + 644;
        aC = gZ + 645;
        aD = gZ + 720;
        aE = gZ + 721;
        aF = gZ + 722;
        aG = gZ + 723;
        aH = gZ + 800;
        aI = gZ + 801;
        aJ = gZ + 802;
        aK = gZ + 832;
        aL = gZ + 833;
        aM = gZ + 864;
        aN = gZ + 865;
        aO = gZ + 866;
        aP = gZ + 867;
        aQ = gZ + 868;
        aR = gZ + 869;
        aS = gZ + 870;
        aT = gZ + 871;
        aU = gZ + 928;
        aV = gZ + 929;
        aW = gZ + 1024;
        aX = gZ + 1025;
        aY = gZ + 1026;
        aZ = gZ + 1027;
        ba = gZ + 1028;
        bb = gZ + 1029;
        bc = gZ + 1040;
        bd = gZ + 1041;
        be = gZ + 1056;
        bf = gZ + 1057;
        bg = gZ + 1058;
        bh = gZ + 1059;
        bi = gZ + 1088;
        bj = gZ + 1280;
        bk = gZ + 1281;
        bl = gZ + 1282;
        bm = gZ + 1283;
        bn = gZ + 1296;
        bo = gZ + 1536;
        bp = gZ + 1537;
        bq = d;
        br = a(gP, e);
        bs = a(gP, n);
        bt = a(gP, be);
        bu = a(gP, bf);
        bv = a(gP, bg);
        bw = a(gP, bh);
        bx = a(gP, k);
        by = a(gP, g);
        bz = b(gP, g);
        bA = a(gP, f);
        bB = a(gP, o);
        bC = a(gP, m);
        bD = a(gP, aH);
        bE = a(gP, aI);
        bF = a(gP, aJ);
        bG = a(gP, aX);
        bH = a(gP, aW);
        bI = a(gP, aY);
        bJ = a(gP, aZ);
        bK = a(gP, ba);
        bL = a(gP, bb);
        bM = a(gP, av);
        bN = a(gP, s);
        bO = a(gP, ae);
        bP = a(gP, af);
        bQ = a(gP, ag);
        bR = a(gP, bj);
        bS = a(gP, bk);
        bT = b(gP, aE);
        bU = a(gP, aE);
        bV = a(gP, ab);
        bW = b(gP, aG);
        bX = a(gP, aG);
        bY = gZ + 672;
        bZ = gZ + 872;
        ca = b(gP, bY);
        cb = a(gP, bY);
        cc = a(gP, bZ);
        cd = a(gP, ah);
        ce = d;
        cf = a(gR, e);
        cg = a(gR, n);
        ch = a(gR, o);
        ci = a(gR, f);
        cj = a(gR, ai);
        ck = a(gR, k);
        cl = a(gR, g);
        cm = b(gR, g);
        cn = a(gR, aH);
        co = a(gR, aI);
        cp = a(gR, P);
        cq = a(gR, j);
        cr = a(gR, r);
        cs = b(gR, r);
        ct = a(gR, q);
        cu = a(gR, ah);
        cv = b(gR, ah);
        cw = a(gR, I);
        cx = b(gR, I);
        cy = a(gR, x);
        cz = a(gR, m);
        cA = a(gR, w);
        cB = a(gR, aj);
        cC = a(gR, bf);
        cD = a(gR, bg);
        cE = a(gR, bh);
        cF = a(gR, ae);
        cG = a(gR, af);
        cH = a(gR, ag);
        cI = a(gR, aX);
        cJ = a(gR, aY);
        cK = a(gR, aW);
        cL = a(gR, aZ);
        cM = a(gR, ba);
        cN = a(gR, bb);
        cO = a(gR, aC);
        cP = b(gR, aC);
        cQ = a(gR, u);
        cR = gZ + 1332;
        cS = b(gR, H);
        cT = a(gR, cR);
        cU = a(gR, aG);
        cV = a(gR, aU);
        cW = d;
        cX = a(gQ, k);
        cY = a(gQ, e);
        cZ = a(gQ, n);
        da = a(gQ, f);
        db = a(gQ, aH);
        dc = a(gQ, aI);
        dd = a(gQ, aX);
        de = a(gQ, aY);
        df = a(gQ, aW);
        dg = a(gQ, g);
        dh = b(gQ, g);
        di = a(gQ, aN);
        dj = a(gQ, ak);
        dk = a(gQ, Q);
        dl = a(gQ, as);
        dm = a(gQ, T);
        dn = a(gQ, aZ);
        _flddo = a(gQ, ba);
        dp = a(gQ, bb);
        dq = a(gQ, al);
        dr = a(gQ, bf);
        ds = a(gQ, bg);
        dt = a(gQ, bh);
        du = a(gQ, j);
        dv = a(gQ, ae);
        dw = a(gQ, af);
        dx = a(gQ, ag);
        dy = a(gQ, H);
        dz = a(gQ, aG);
        dA = a(gQ, aU);
        dB = a(gQ, p);
        dC = a(gQ, ah);
        dD = d;
        dE = a(gS, k);
        dF = a(gS, e);
        dG = a(gS, n);
        dH = a(gS, f);
        dI = a(gS, o);
        dJ = a(gS, aH);
        dK = a(gS, aX);
        dL = a(gS, aY);
        dM = a(gS, aW);
        dN = a(gS, s);
        dO = b(gS, g);
        dP = a(gS, g);
        dQ = a(gS, aI);
        dR = a(gS, ak);
        dS = a(gS, al);
        dT = a(gS, av);
        dU = a(gS, aZ);
        dV = a(gS, ba);
        dW = a(gS, bb);
        dX = a(gS, bf);
        dY = a(gS, bg);
        dZ = a(gS, bh);
        ea = a(gS, j);
        eb = a(gS, ae);
        ec = a(gS, af);
        ed = a(gS, ag);
        ee = a(gS, aG);
        ef = d;
        eg = a(gT, k);
        eh = a(gT, e);
        ei = a(gT, n);
        ej = a(gT, f);
        ek = a(gT, aH);
        el = a(gT, aI);
        em = a(gT, aX);
        en = a(gT, aY);
        eo = a(gT, aW);
        ep = a(gT, g);
        eq = b(gT, g);
        er = a(gT, ak);
        es = a(gT, Q);
        et = a(gT, as);
        eu = a(gT, T);
        ev = a(gT, aZ);
        ew = a(gT, ba);
        ex = a(gT, bb);
        ey = a(gT, al);
        ez = a(gT, at);
        eA = a(gT, ab);
        eB = a(gT, s);
        eC = a(gT, o);
        eD = a(gT, aN);
        eE = a(gT, bf);
        eF = a(gT, bg);
        eG = a(gT, bh);
        eH = a(gT, j);
        eI = a(gT, ae);
        eJ = a(gT, af);
        eK = a(gT, R);
        eL = a(gT, ag);
        eM = a(gT, aG);
        eN = a(gT, aU);
        eO = d;
        eP = a(gV, k);
        eQ = a(gV, e);
        eR = a(gV, n);
        eS = a(gV, f);
        eT = a(gV, o);
        eU = a(gV, aH);
        eV = a(gV, aX);
        eW = a(gV, aW);
        eX = a(gV, at);
        eY = a(gV, ab);
        eZ = a(gV, s);
        fa = a(gV, g);
        fb = b(gV, g);
        fc = a(gV, aI);
        fd = a(gV, ak);
        fe = a(gV, al);
        ff = a(gV, av);
        fg = a(gV, aZ);
        fh = a(gV, ba);
        fi = a(gV, bb);
        fj = a(gV, bf);
        fk = a(gV, bg);
        fl = a(gV, bh);
        fm = a(gV, j);
        fn = a(gV, ae);
        fo = a(gV, af);
        fp = a(gV, ag);
        fq = a(gV, aK);
        fr = a(gV, aL);
        fs = gZ + 834;
        ft = gZ + 1089;
        fu = b(gV, fs);
        fv = a(gV, fs);
        fw = a(gV, T);
        fx = a(gV, aN);
        fy = a(gV, u);
        fz = a(gV, ax);
        fA = a(gV, al);
        fB = a(gV, ah);
        fC = a(gV, I);
        fD = a(gV, ft);
        fE = d;
        fF = a(gX, f);
        fG = a(gX, n);
        fH = a(gX, k);
        fI = a(gX, g);
        fJ = b(gX, g);
        fK = a(gX, j);
        fL = a(gX, aH);
        fM = a(gX, e);
        fN = a(gX, C);
        fO = a(gX, bj);
        fP = a(gX, bk);
        fQ = a(gX, m);
        fR = a(gX, bl);
        fS = b(gX, bl);
        fT = a(gX, bm);
        fU = a(gX, t);
        fV = d;
        fW = a(gY, f);
        fX = a(gY, n);
        fY = a(gY, k);
        fZ = a(gY, g);
        ga = b(gY, g);
        gb = a(gY, j);
        gc = a(gY, aH);
        gd = a(gY, e);
        ge = a(gY, aI);
        gf = a(gY, t);
        gg = a(gY, H);
        gh = a(gY, s);
        gi = b(gY, al);
        gj = d;
        gk = a(gU, k);
        gl = a(gU, e);
        gm = a(gU, n);
        gn = a(gU, f);
        go = a(gU, o);
        gp = a(gU, aH);
        gq = a(gU, aI);
        gr = a(gU, aX);
        gs = a(gU, aW);
        gt = a(gU, g);
        gu = b(gU, g);
        gv = a(gU, aZ);
        gw = a(gU, ba);
        gx = a(gU, bb);
        gy = a(gU, al);
        gz = a(gU, bf);
        gA = a(gU, bg);
        gB = a(gU, bh);
        gC = a(gU, ag);
        gD = a(gU, u);
        gE = a(gU, aG);
        gF = a(gU, aU);
        gG = a(gU, p);
        gH = a(gU, bj);
        gI = a(gU, q);
        gJ = a(gU, aN);
        gK = a(gU, r);
        gL = a(gU, l);
        gM = a(gU, bo);
        gN = a(gU, bp);
    }
}
